name: Packages prune
on:
  registry_package:
    types: [published]
jobs:
  packages-prune:
    runs-on: ubuntu-latest
    steps:
    - name: Prune
      uses: vlaurin/action-ghcr-prune@v0.5.0
      with:
        token: ${{ secrets.GHCR_TOKEN }}
        #organization: your-org
        user: arielmendz
        container: coretto
        dry-run: true # Dry-run first, then change to `false`
        keep-last: 5
        keep-tags-regexes: |
          ^RC-
        prune-untagged: true
